# Generated by Django 5.0.7 on 2024-08-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='name',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='dateCreated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='totalLost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='totalPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='totalWon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
