# Generated by Django 5.1 on 2024-08-12 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_siteuser_name_siteuser_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
