# Generated by Django 5.0.7 on 2024-08-01 13:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_siteuser_name_siteuser_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to=users.models.rename_avatar),
        ),
    ]
