# Generated by Django 5.0.7 on 2024-08-01 15:36

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_siteuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/shared_media/default_avatar.jpg', null=True, upload_to=users.models.rename_avatar),
        ),
    ]
