version: '3'

services:
  frontend:
    container_name: trans_front
    build:
      context: ./frontend
    ports:
      - "${FRONT_PORT}:443"
    networks:
      - trans_net
    restart: on-failure
    depends_on:
      - backend
    volumes:
      - ./frontend/logs:/var/log/nginx   # 403 Forbidden error... why ?

  backend:
    container_name: trans_back
    build: 
      context: ./backend
    expose: 
    - "${BACK_PORT}"
    depends_on:
      - database

  database:
    container_name: trans_db
    image: postgres:16
    restart: on-failure:5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PORT=${DB_PORT}

volumes:
  db_data:

networks:
  trans_net:
    name: trans_net
    driver: bridge