# Generated by Django 5.0.7 on 2024-07-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
