const translations =
{
	en: {
		profile: 'Profile',
		play: 'Play',
		leaderboard: 'Leaderboard', 
		language: 'Language',
		whoarewe: 'Who are We ?',
		legalnotice: 'Legal Notices',
		spring: 'Spring 2024',
		legalbody1: 'This site is for educational purposes only. None of the data collected (name, first name, email address, etc...) will be used outside of this site and will not be shared with a third party.',
		legalbody2: 'This website is the property of the members of its dev team and 42Born2Code.',
		about: 'We are a student team from 42Born2Code at Paris.',
		chat: 'Chat',
		username: 'Username',
		invalidusername: 'Invalid Username',
		password: 'Password',
		email: 'email',
		log_in: 'Log in',
		noaccountyet: 'Don\'t have an account yet?',
		alreadyaccount: 'Already have an account?',
		registerhere: 'Register here',
		registertitle: 'Registration',
		deleteaccount: 'Delete Account',
		member_since: 'Member since',
		online: 'Online',
		offline: 'Offline',
		overallstats: 'Overall Statistics',
		totalplayed: 'Total played',
		totalwon: 'Total won',
		totallost: 'Total lost',
		winrate: 'Win rate',
		matchhistory: 'Match history',
		nomatchplayed: 'No match found for this player',
		friendslist: 'Friends List',
		removefriend: 'Remove Friend',
		addfriend: "Add Friend",
		selectgamemode: 'Select game mode',
		versusbot: 'Versus Bot',
		versushuman: 'Versus Human',
		tournament: 'Tournament',
		tournamenthowmanyplayers: 'How many players will play?',
		starttournament: 'Start tournament',
		enterplayername: 'Enter player name',
		tournamentwinner: 'Tournament winner',
		restarttournament: 'Restart tournament',
		nextmatch: 'Next match',
		playagain: 'Play again',
		wins: ' wins this game !',
		submit: 'Confirm',
		challengername: 'Challenger Name',
		firstmatch: 'First Match',
		secondmatch: 'Second Match',
		finalmatch: 'Final Match',
		otp_verify_title: 'Setup Two Factor Authentication',
		otp_verify_cta: 'Verify',
		otp: 'OTP',
		invalidotp: 'Invalid OTP',
		otpnotmandatory: 'You can choose not to use double authentication by leaving this page.',
		ignoreotp: 'Ignore OTP',
		player1: 'Player 1',
		player2: 'Player 2',
		player3: 'Player 3',
		player4: 'Player 4',
	},
	fr: {
		profile: 'Profil',
		play: 'Jouer',
		leaderboard: 'Classement',
		language: 'Langue',
		whoarewe: 'Qui sommes nous ?',
		legalnotice: 'Mentions Légales',
		spring: 'Printemps 2024',
		legalbody1: 'Ce site est à caractère pédagogique uniquement. Aucune des données recueillies (nom, prénom, adresse mail, etc...) ne sera utilisée en dehors de ce site et ne sera communiquée à un tiers.',
		legalbody2: 'Ce site est la propriété des membres de son équipe de devs et de 42Born2Code.',
		about: 'Nous sommes une équipe d\'étudiants de l\'école de 42Born2Code à Paris.',
		chat: 'Tchat',
		username: 'Nom d\'utilisateur',
		invalidusername: 'Nom d\'utilisateur invalide',
		password: 'Mot de passe',
		email: 'email',
		log_in: 'Connexion',
		noaccountyet: 'Pas encore de compte?',
		alreadyaccount: 'Déjà membre ?',
		registerhere: 'Inscrivez-vous',
		registertitle: 'Inscription',
		deleteaccount: 'Supprimer le compte',
		member_since: 'Membre depuis le',
		online: 'En ligne',
		offline: 'Offline',
		overallstats: 'Statistiques générales',
		totalplayed: 'Total joué',
		totalwon: 'Total gagné',
		totallost: 'Total perdu',
		winrate: 'Taux de victoire',
		matchhistory: 'Historique des matchs',
		nomatchplayed: 'Aucun match trouvé pour ce joueur',
		friendslist: 'Liste d\'amis',
		removefriend: 'Retirer Ami',
		addfriend: "Ajouter Ami",
		selectgamemode: 'Sélectionner le mode de jeu',
		versusbot: 'Contre un bot',
		versushuman: 'Contre un humain',
		tournament: 'Tournoi',
		tournamenthowmanyplayers: 'Combien de joueurs vont jouer ?',
		starttournament: 'Démarrer le tournoi',
		enterplayername: 'Entrez le nom du joueur',
		tournamentwinner: 'Vainqueur du tournoi',
		restarttournament: 'Redémarrer le tournoi',
		nextmatch: 'Prochain match',
		playagain: 'Rejouer',
		wins: ' remporte cette partie !',
		submit: 'Confirmer',
		challengername: 'Nom du challenger',
		firstmatch: 'Premier match',
		secondmatch: 'Deuxième match',
		finalmatch: 'Match final',
		otp_verify_title: 'Configurer l\'authentification à deux facteurs',
		otp_verify_cta: 'Vérifier',
		otp: 'OTP',
		invalidotp: 'OTP invalide',
		otpnotmandatory: 'Vous pouvez choisir de ne pas utiliser l\'authentification à deux facteurs en quittant cette page.',
		ignoreotp: 'Ignorer l\'OTP',
		player1: 'Joueur 1',
		player2: 'Joueur 2',
		player3: 'Joueur 3',
		player4: 'Joueur 4'
	},
	ch: {
		profile: '个人资料',
		play: '玩',
		leaderboard: '排行榜',
		language: '语言',
		whoarewe: '我们是谁？',
		legalnotice: '法律声明',
		spring: '2024年春季',
		legalbody1: '本网站仅用于教育目的。收集的任何数据（姓名、名字、电子邮件地址等）都不会在本网站之外使用，也不会与第三方共享。',
		legalbody2: '本网站是其开发团队成员和42Born2Code的财产。',
		about: '我们是巴黎42Born2Code的学生团队。',
		chat: '聊天',
		username: '用户名',
		invalidusername: '用户名无效',
		password: '密码',
		email: '电子邮件',
		log_in: '登录',
		noaccountyet: '还没有账户吗？',
		alreadyaccount: '已有账号？',
		registerhere: '在这里注册',
		registertitle: '注册',
		deleteaccount: '删除账户',
		member_since: '会员自',
		online: '在线',
		offline: '离线',
		overallstats: '总体统计',
		totalplayed: '总场次',
		totalwon: '总胜场',
		totallost: '总负场',
		winrate: '胜率',
		matchhistory : '数学史',
		nomatchplayed: '未找到该玩家的比赛',
		friendslist: '好友列表',
		removefriend: '移除好友',
		addfriend: "添加好友",
		selectgamemode: '选择游戏模式',
		versusbot: '对战机器人',
		versushuman: '对战真人',
		tournament: '锦标赛',
		tournamenthowmanyplayers: '有多少玩家会参与？',
		starttournament: '开始锦标赛',
		enterplayername: '输入玩家姓名',
		tournamentwinner: '锦标赛冠军',
		restarttournament: '重新开始锦标赛',
		nextmatch: '下一场比赛',
		playagain: '再玩一次',
		wins: ' 赢得了这场比赛！',
		submit: '确认',
		challengername: '挑战者名称',
		firstmatch: '第一场比赛',
		secondmatch: '第二场比赛',
		finalmatch: '决赛',
		otp_verify_title: '设置双因素认证',
		otp_verify_cta: '验证',
		otp: 'OTP',
		invalidotp: '无效的OTP',
		otpnotmandatory: '您可以选择离开此页面而不使用双因素认证。',
		ignoreotp: '忽略OTP',
		player1: '玩家 1',
		player2: '玩家 2',
		player3: '玩家 3',
		player4: '玩家 4'
	},
	jp: {
		profile: 'プロフィール',
		play: 'プレイ',
		leaderboard: 'リーダーボード',
		language: '言語',
		whoarewe: '私たちについて',
		legalnotice: '法的通知',
		spring: '2024年春',
		legalbody1: 'このサイトは教育目的のみです。収集されたデータ（名前、名字、電子メールアドレスなど）はこのサイトの外では使用されず、第三者と共有されません。',
		legalbody2: 'このウェブサイトは、その開発チームのメンバーと42Born2Codeの所有物です。',
		about: '私たちはパリの42Born2Codeからの学生チームです。',
		chat: 'チャット',
		username: 'ユーザー名',
		invalidusername: '無効なユーザー名',
		password: 'パスワード',
		email: 'メール',
		log_in: 'ログイン',
		noaccountyet: 'まだアカウントを持っていませんか？',
		alreadyaccount: '既にアカウントをお持ちですか？',
		registerhere: 'ここで登録',
		registertitle: '登録',
		deleteaccount: 'アカウントを削除',
		member_since: '登録日',
		online: 'オンライン',
		offline: 'オフライン',
		overallstats: '全体統計',
		totalplayed: '総プレイ数',
		totalwon: '総勝利数',
		totallost: '総敗北数',
		winrate: '勝率',
		matchhistory: '数学の歴史',
		nomatchplayed: 'このプレイヤーに該当する試合が見つかりません',
		friendslist: '友達リスト',
		removefriend: '友達を削除',
		addfriend: "友達を追加",
		selectgamemode: 'ゲームモードを選択',
		versusbot: 'ボット対戦',
		versushuman: '人間対戦',
		tournament: 'トーナメント',
		tournamenthowmanyplayers: '何人がプレイしますか？',
		starttournament: 'トーナメントを開始',
		enterplayername: 'プレイヤー名を入力してください',
		tournamentwinner: 'トーナメント優勝者',
		restarttournament: 'トーナメントを再開始する',
		nextmatch: '次の試合',
		playagain: 'もう一度プレイ',
		wins: ' このゲームに勝ちました！',
		submit: '確認',
		challengername: '挑戦者の名前',
		firstmatch: '第一試合',
		secondmatch: '第二試合',
		finalmatch: '決勝戦',
		otp_verify_title: '二段階認証を設定する',
		otp_verify_cta: '確認する',
		otp: 'OTP',
		invalidotp: '無効なOTP',
		otpnotmandatory: 'このページを離れることで二段階認証を使用しないことを選択できます。',
		ignoreotp: 'OTPを無視する',
		player1: 'プレイヤー 1',
		player2: 'プレイヤー 2',
		player3: 'プレイヤー 3',
		player4: 'プレイヤー 4'
	}
};

// get translation for the given key
export function getTranslationForKey(key, language)
{
	// if the key exists, return the translation, else return the key
	if (translations[language] && translations[language][key])
		return translations[language][key];
	return key;
}

export function applyLanguage()
{
	const language = localStorage.getItem('language') || 'en';
	document.documentElement.lang = language;

	// select all elements to translate
	var elementsToTranslate = document.querySelectorAll('[data-translate]');

	// each element
	elementsToTranslate.forEach(function(element) {
		var key = element.getAttribute('data-translate');
		var translation = getTranslationForKey(key, language); // Tu devrais implémenter cette fonction
		element.textContent = translation;
	});
}

export function setLanguage(language)
{
	const currentLanguage = localStorage.getItem('language') || 'en';

	// check if already the current language
	if (language !== currentLanguage) {
		localStorage.setItem('language', language);
		document.documentElement.lang = language;
		location.reload();
	}
}

window.setLanguage = setLanguage;